### ISSUE TITLE
Fatal error when build the project for linux.

### ISSUE THREAD

**Issue by marfgold1** [native-m/ShaderBoi#2]
Build log while compiling the project with `make -f Makefile`
<pre>make: pkg-config: Command not found
make: pkg-config: Command not found
Compiling SBGlslTokeniser.cpp
Compiling SBCodeEditor.cpp
Compiling SBSubCodeEditor.cpp
Compiling SBShaderView.cpp
Compiling GLView.cpp
Compiling SBTimer.cpp
<b>../../Source/SBTimer.cpp:2:10:</b> <font color="#EF2929"><b>fatal error: </b></font>Windows.h: No such file or directory
 #include <font color="#EF2929"><b>&lt;Windows.h&gt;</b></font>
          <font color="#EF2929"><b>^~~~~~~~~~~</b></font>
compilation terminated.
make: *** [Makefile:176: build/intermediate/Debug/SBTimer_5ca0c3b7.o] Error 1
</pre>

Perhaps you should consider cross-platform header for it rather than Windows-only header, tq @native-m

**Comment by native-m** [comment]
Fixed

**Comment by marfgold1** [comment]
Would be useful if you reference the commit that fix this issue by adding `Fixes #x` with x is the issue number in the commit message
